Add Tekton home page in Japanese
fujitsu-cdf/website pull request #7
Opened 2021-04-13 02:20 UTC by takoh-yuuichiro

# Changes

Related to issue [#243](https://github.com/tektoncd/website/issues/243)
- Add Tekton home page texts in Japanese
- Add Japanese translation to
    - ja.toml
    - privacy-notice-ja.html 
    - manifesto-ja.html 
    - partners-alternate-ja.html
- Add Japanese language settings
- Add a language selector for the navigation bar

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

2021-04-13 05:00 UTC, kobaji requested changes
まだ途中ですが、とりあえずこれまでのところで気になった部分をコメントしました。
現在1点です。

2021-04-13 05:00 UTC, kobaji commented on content/ja/_index.html
> +Knative、および他の多くの一般的なCI / CDツールで動作します。
`CI / CD`

すごく細かいですが、`CI/CD`にせず、半角スペースを空けたのには意図がありますか？英語版では`CI/CD`のようにスペースがないと思いますが。

2021-04-13 05:00 UTC, kobaji commented on content/ja/_index.html
> +Knative、および他の多くの一般的なCI / CDツールで動作します。
念のため、他の日本語化ファイルで表記が統一されているかご確認をお願いいたします。

2021-04-13 05:20 UTC, Martsings commented on i18n/ja.toml
> +other = "Posts in"
post_*が全部英語のままとなっていますが、こういう仕様でしょうか？

2021-04-14 00:40 UTC, kobaji commented on layouts/shortcodes/blocks/manifesto-ja.html
> +				<h3>Tektonは<a href="https://cd.foundation/">継続的デリバリーファウンデーション</a>プロジェクトです。</h3>
`<h3>Tektonは<a href="https://cd.foundation/">継続的デリバリーファウンデーション</a>プロジェクトです。</h3>`
↓
`<h3>Tektonは<a href="https://cd.foundation/">Continuous Delivery Foundation</a>のプロジェクトです。</h3>`

はいかがでしょうか。

つまり
・`継続的デリバリーファウンデーション`は`Continuous Delivery Foundation`のままにする(固有名詞なので)。
・`「の」プロジェクト`にする

を検討していただきたい、というコメントです。

参考：
英語だと以下のようです。
https://tekton.dev/

> Tekton is a Continuous Delivery Foundation project.

2021-04-14 00:46 UTC, kobaji commented on layouts/shortcodes/blocks/partners-alternate-ja.html
> +                    Tektonプロジェクトに関与している組織及び個人については<a href="https://github.com/tektoncd/friends">こちら</a>
細かいですが。
`組織及び個人`

英語ページ(https://tekton.dev/)では `individuals and organizations`つまり「個人および組織」となっています。順番を合わせなかった意図はありますでしょうか。
特に意図がなければ、揃えてもよいと思いました。

2021-04-14 00:49 UTC, kobaji commented on layouts/shortcodes/blocks/partners-alternate-ja.html
> +                    Tektonプロジェクトに関与している組織及び個人については<a href="https://github.com/tektoncd/friends">こちら</a>
`及び`

他の翻訳箇所は`および`(ひらがな)になっているようなので、表記ゆれがあります。ひらがなに統一いただけますでしょうか。

念のため類似見直しもお願いいたします。

2021-04-14 00:54 UTC, kobaji commented on layouts/shortcodes/blocks/showcase-ja.html
> +					<div class="text-left">
- `Tektonは強力で柔軟性のある `：`ある`の後ろに半角スペース` `がある
- `CD/CDシステム構築用のオープンソースフレームワークで、`：`で、`の後ろに半角スペースがない

細かいですが、統一できますか？
類似見直しが大変な割に効果的ではないと思うので、マージされて今後記事修正とか記事追加とかになった場合に併せて実施でもよいと思います(その場合、失念防止のためにチケットの説明部分にその旨残しておいていただければと思います)。

2021-04-14 00:58 UTC, kobaji commented on config.toml
> +description = "クラウドネイティブ CI/CD"
小林コメントWIP
ロゴについてコメントしようと思っている

2021-04-15 02:52 UTC, takoh-yuuichiro commented on content/ja/_index.html
> +Knative、および他の多くの一般的なCI / CDツールで動作します。
指摘個所について、9268-wk側ソースをスペースのない"CI/CD"に修正しました。
なお、他の日本語化ファイルでは全てスペースのない"CI/CD"となっていました。

2021-04-15 02:53 UTC, takoh-yuuichiro commented on i18n/ja.toml
> +other = "Posts in"
トップページとは関係しない場所のため、翻訳していませんでした。今後他のページの日本語化を行う機会があれば、それに合わせて翻訳する予定です。

2021-04-15 02:53 UTC, takoh-yuuichiro commented on layouts/shortcodes/blocks/manifesto-ja.html
> +				<h3>Tektonは<a href="https://cd.foundation/">継続的デリバリーファウンデーション</a>プロジェクトです。</h3>
指摘個所について、9268-wk側ソースを修正案の通りに修正しました。

2021-04-15 02:54 UTC, takoh-yuuichiro commented on layouts/shortcodes/blocks/partners-alternate-ja.html
> +                    Tektonプロジェクトに関与している組織及び個人については<a href="https://github.com/tektoncd/friends">こちら</a>
指摘個所について、9268-wk側ソースを"個人および組織"に修正しました。

2021-04-15 02:54 UTC, takoh-yuuichiro commented on layouts/shortcodes/blocks/partners-alternate-ja.html
> +                    Tektonプロジェクトに関与している組織及び個人については<a href="https://github.com/tektoncd/friends">こちら</a>
指摘個所について、9268-wk側ソースを"個人および組織"に修正しました。
なお、類似見直しの結果、同様の揺れは検出されませんでした。

2021-04-15 02:55 UTC, takoh-yuuichiro commented on layouts/shortcodes/blocks/showcase-ja.html
> +					<div class="text-left">
指摘個所について、9268-wk側ソースの半角スペース有無を統一しました。
なお、他の日本語化ファイルについて、ご指摘の半角スペースがないことを確認しました。

2021-04-15 02:56 UTC, takoh-yuuichiro commented on config.toml
> +description = "クラウドネイティブ CI/CD"
見直しの結果、１ファイル反映漏れがありました。
layouts/shortcodes/blocks/cover.htmlで、Tektonのロゴを多言語でも表示できるように修正しましたが、それがブランチへ反映漏れしていました。
9268-wkに反映しておきました。

2021-04-15 05:58 UTC, merged